USE [OneGISDB]
GO

IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FOLDERS]') AND TYPE IN (N'U'))
DROP TABLE [dbo].[FOLDERS]
GO

CREATE TABLE [dbo].[FOLDERS](
	[USERNAME] [VARCHAR](100) NOT NULL,
	[ID] [UNIQUEIDENTIFIER] NOT NULL,
	[TITLE] [VARCHAR](100) NOT NULL,
	[CREATED] [SMALLDATETIME] NOT NULL,
 CONSTRAINT PK_FOLDERS_ID PRIMARY KEY CLUSTERED (ID)
)
GO


IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_CREATE_FOLDER]') AND TYPE IN (N'P'))
DROP PROCEDURE [dbo].[SP_CREATE_FOLDER]
GO
/*
CREATE PROCEDURE [dbo].[SP_CREATE_FOLDER]
	@USERNAME VARCHAR(100),
	@FOLDERNAME VARCHAR(100),
	@GUID UNIQUEIDENTIFIER OUTPUT,
	@DATETIME SMALLDATETIME OUTPUT
AS
BEGIN
	SET @GUID = NEWID();
	SET @DATETIME = SYSUTCDATETIME();
	INSERT INTO [dbo].[FOLDERS] ([USERNAME],[ID],[TITLE],[CREATED])VALUES (@USERNAME,@GUID,@FOLDERNAME,@DATETIME);
END
GO
*/

CREATE PROCEDURE [dbo].[SP_CREATE_FOLDER]
	@USERNAME VARCHAR(100),
	@FOLDERNAME VARCHAR(100),
	@GUID UNIQUEIDENTIFIER,
	@DATETIME SMALLDATETIME OUTPUT
AS
BEGIN
	SET @DATETIME = SYSUTCDATETIME();
	INSERT INTO [dbo].[FOLDERS] ([USERNAME],[ID],[TITLE],[CREATED])VALUES (@USERNAME,@GUID,@FOLDERNAME,@DATETIME);
END
GO




--TRUNCATE TABLE [OneGISDB].[dbo].[FOLDERS]

/*
DECLARE @RC int;
DECLARE @USERNAME varchar(100);
DECLARE @FOLDERNAME varchar(100);
DECLARE @GUID uniqueidentifier;
DECLARE @DATETIME smalldatetime;

SET @USERNAME = 'yogeshdhanapal';
SET @FOLDERNAME = 'Folder1';

EXECUTE [dbo].[SP_CREATE_FOLDER] @USERNAME,@FOLDERNAME,@GUID OUTPUT,@DATETIME OUTPUT
SELECT @GUID;SELECT @DATETIME;
*/